#!/bin/bash

# UNINSTALL NATIONAL INSTRUMENTS DRIVERS 3.5.0f1, 3.6.0, 3.7.0, 14.0.0, 15.0.0
# https://gist.github.com/jpgill86/2342ee23241120de41e505194e7de178
#
# This script was created from the lists of files in several Uninstall.txt files
#
# NI-DAQmx Base 3.5.0f1, 3.6.0, 3.7.0, 14.0.0, 15.0.0
#   /Applications/National Instruments/NI-DAQmx Base/Uninstall.txt
#
# NI-VISA 5.1, 5.2, 5.4, 14.0.0, 15.0.0
#   /Applications/National Instruments/NI-VISA/Uninstall.txt
#
# NI I/O Trace v 3.0.0
#   /Applications/National Instruments/NI IO Trace/Uninstall.txt
#
# NI-PAL
#   /Library/Application Support/National Instruments/nipal/Uninstall.txt
#
# NI-RPC
#   /Library/Application Support/National Instruments/nirpc/Uninstall.txt
#
# NI System API
#   /Library/Application Support/National Instruments/nisysapi/Uninstall.txt
#
# Components that will be uninstalled:
#   NI-DAQmx Base Common
#   NI-DAQmx Base C Interface
#   NI-DAQmx Base LabVIEW
#   NI-DAQmx Base USB Support
#   NI-VISA Runtime
#   NI-VISA Development Support
#   NI-VISA Configuration
#   NI-VISA Server
#   NI-PAL
#   NI-RPC
#   NI MAX
#   NI Xerces
#   NI I/O Trace Application
#   NI System API
#   LabVIEW Runtime Engine
#   Installer Receipt Components
#   Per-User Preferences

# Require that the user is root
if [[ "$UID" -ne 0 ]]; then
    echo >&2 "Aborted: superuser privileges needed (rerun with sudo)"
    exit 1
fi

launchctl remove nilxid
rm -rf "/Applications/National Instruments"
rm -rf "/Library/Application Support/National Instruments"
rm -rf /Library/Extensions/NiViPciK.kext
rm -rf /Library/Extensions/nipalk.kext
rm -rf /Library/Extensions/niusb9162k.kext
rm -rf /Library/Frameworks/LabVIEW*
rm -rf /Library/Frameworks/lib67xx.framework
rm -rf /Library/Frameworks/libDIO96.framework
rm -rf /Library/Frameworks/libESeries.framework
rm -rf /Library/Frameworks/libmiteDma.framework
rm -rf /Library/Frameworks/libmxBaseSessionTable.framework
rm -rf /Library/Frameworks/libMSeries.framework
rm -rf /Library/Frameworks/libSSeries.framework
rm -rf /Library/Frameworks/libUSB-92xx.framework
rm -rf /Library/Frameworks/NI-RPC.framework
rm -rf /Library/Frameworks/nidaqmxbase.framework
rm -rf /Library/Frameworks/nidaqmxbaselv.framework
rm -rf /Library/Frameworks/nipalu.framework
rm -rf /Library/Frameworks/NiSpyLog.framework
rm -rf /Library/Frameworks/nisysapi.framework
rm -rf /Library/Frameworks/nixerces.framework
rm -rf /Library/Frameworks/VISA.framework
rm -rf /Library/LaunchDaemons/com.ni.nipal.plist
rm -rf /Library/LaunchDaemons/nilxid.plist
rm -rf /Library/Preferences/NIvisa
rm -rf /Library/Receipts/nipali.pkg
rm -rf /Library/Receipts/nirpci.pkg
rm -rf /Library/Receipts/nivisaconfigurationi.pkg
rm -rf /Library/Receipts/nivisadevelopmenti.pkg
rm -rf /Library/Receipts/nivisaruntimei.pkg
rm -rf /Library/Receipts/nivisaserveri.pkg
rm -rf /Library/StartupItems/nipal
rm -rf /System/Library/Extensions/NiViPciK.kext
rm -rf /System/Library/Extensions/nipalk.kext
rm -rf /System/Library/Extensions/niusb9162k.kext
rm -rf /usr/local/bin/lsni
rm -rf /usr/local/libexec/nipald
rm -rf /usr/sbin/nipalsm
rm -rf /usr/sbin/palModuleMgr.sh
rm -rf /var/db/receipts/com.ni.*
rm -rf ~/.nispy.ini
pkgutil --forget com.ni.LabVIEWRuntime*
pkgutil --forget com.ni.pkg.daqmxbase.cinterface
pkgutil --forget com.ni.pkg.daqmxbase.cinterface.LibFwk
pkgutil --forget com.ni.pkg.daqmxbase.common
pkgutil --forget com.ni.pkg.daqmxbase.common.LibAppSupp
pkgutil --forget com.ni.pkg.daqmxbase.common.LibFwk
pkgutil --forget com.ni.pkg.daqmxbase.labview*-VIs
pkgutil --forget com.ni.pkg.daqmxbase.usb-support
pkgutil --forget com.ni.pkg.daqmxbase.usb-support.LibExt
pkgutil --forget com.ni.pkg.daqmxbase.usb-support.SysLibExt
pkgutil --forget com.ni.pkg.nipal
pkgutil --forget com.ni.pkg.nivisaconfiguration
pkgutil --forget com.ni.pkg.nivisadevelopment
pkgutil --forget com.ni.pkg.nivisaruntime
pkgutil --forget com.ni.pkg.nivisaserver
pkgutil --forget com.ni.nipali.LibAppSupp.pkg
pkgutil --forget com.ni.nipali.LibFwk.pkg
pkgutil --forget com.ni.nipali.LibLaunchd.pkg
pkgutil --forget com.ni.nipali.LibStartup.pkg
pkgutil --forget com.ni.nipali.SysUserLocalLibExec.pkg
pkgutil --forget com.ni.nipali.SysUsrSbin.pkg
pkgutil --forget com.ni.nisysapi.LibAppSupp.pkg
pkgutil --forget com.ni.nisysapi.LibFwk.pkg
pkgutil --forget com.ni.nisysapi.UsrLocalBin.pkg
pkgutil --forget com.ni.NI-VISA_DevSupp.LibAppSupp.pkg
pkgutil --forget com.ni.NI-VISA_DevSupp.LibPrefs.pkg
pkgutil --forget com.ni.NI-VISA_Runtime.App.pkg
pkgutil --forget com.ni.NI-VISA_Runtime.LibAppSupp.pkg
pkgutil --forget com.ni.NI-VISA_Runtime.LibExt.pkg
pkgutil --forget com.ni.NI-VISA_Runtime.LibLaunchd.pkg
pkgutil --forget com.ni.NI-VISA_Runtime.LibPrefs.pkg
