// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Loop_out_proc24.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Loop_out_proc24::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Loop_out_proc24::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> Loop_out_proc24::ap_ST_fsm_state1 = "1";
const sc_lv<3> Loop_out_proc24::ap_ST_fsm_state2 = "10";
const sc_lv<3> Loop_out_proc24::ap_ST_fsm_state3 = "100";
const sc_lv<32> Loop_out_proc24::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> Loop_out_proc24::ap_const_lv32_2 = "10";
const sc_lv<1> Loop_out_proc24::ap_const_lv1_0 = "0";
const sc_lv<32> Loop_out_proc24::ap_const_lv32_1 = "1";
const sc_lv<10> Loop_out_proc24::ap_const_lv10_0 = "0000000000";
const sc_lv<1> Loop_out_proc24::ap_const_lv1_1 = "1";
const sc_lv<8> Loop_out_proc24::ap_const_lv8_0 = "00000000";
const sc_lv<10> Loop_out_proc24::ap_const_lv10_258 = "1001011000";
const sc_lv<10> Loop_out_proc24::ap_const_lv10_1 = "1";
const sc_lv<10> Loop_out_proc24::ap_const_lv10_320 = "1100100000";
const bool Loop_out_proc24::ap_const_boolean_1 = true;

Loop_out_proc24::Loop_out_proc24(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state3);
    sensitive << ( img_0_data_stream_0_V_full_n );
    sensitive << ( img_0_data_stream_1_V_full_n );
    sensitive << ( img_0_data_stream_2_V_full_n );
    sensitive << ( icmp_ln25_fu_107_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln23_fu_95_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_col_fu_113_p2);
    sensitive << ( p_Val2_s_reg_84 );

    SC_METHOD(thread_icmp_ln23_fu_95_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( p_Val2_1_reg_73 );

    SC_METHOD(thread_icmp_ln25_fu_107_p2);
    sensitive << ( img_0_data_stream_0_V_full_n );
    sensitive << ( img_0_data_stream_1_V_full_n );
    sensitive << ( img_0_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln25_fu_107_p2 );
    sensitive << ( p_Val2_s_reg_84 );

    SC_METHOD(thread_img_0_data_stream_0_V_blk_n);
    sensitive << ( img_0_data_stream_0_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln25_fu_107_p2 );

    SC_METHOD(thread_img_0_data_stream_0_V_din);
    sensitive << ( img_0_data_stream_0_V_full_n );
    sensitive << ( img_0_data_stream_1_V_full_n );
    sensitive << ( img_0_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln25_fu_107_p2 );
    sensitive << ( p_Val2_s_reg_84 );

    SC_METHOD(thread_img_0_data_stream_0_V_write);
    sensitive << ( img_0_data_stream_0_V_full_n );
    sensitive << ( img_0_data_stream_1_V_full_n );
    sensitive << ( img_0_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln25_fu_107_p2 );

    SC_METHOD(thread_img_0_data_stream_1_V_blk_n);
    sensitive << ( img_0_data_stream_1_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln25_fu_107_p2 );

    SC_METHOD(thread_img_0_data_stream_1_V_din);
    sensitive << ( img_0_data_stream_0_V_full_n );
    sensitive << ( img_0_data_stream_1_V_full_n );
    sensitive << ( img_0_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln25_fu_107_p2 );

    SC_METHOD(thread_img_0_data_stream_1_V_write);
    sensitive << ( img_0_data_stream_0_V_full_n );
    sensitive << ( img_0_data_stream_1_V_full_n );
    sensitive << ( img_0_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln25_fu_107_p2 );

    SC_METHOD(thread_img_0_data_stream_2_V_blk_n);
    sensitive << ( img_0_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln25_fu_107_p2 );

    SC_METHOD(thread_img_0_data_stream_2_V_din);
    sensitive << ( img_0_data_stream_0_V_full_n );
    sensitive << ( img_0_data_stream_1_V_full_n );
    sensitive << ( img_0_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln25_fu_107_p2 );

    SC_METHOD(thread_img_0_data_stream_2_V_write);
    sensitive << ( img_0_data_stream_0_V_full_n );
    sensitive << ( img_0_data_stream_1_V_full_n );
    sensitive << ( img_0_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln25_fu_107_p2 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln23_fu_95_p2 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_row_fu_101_p2);
    sensitive << ( p_Val2_1_reg_73 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_0_data_stream_0_V_full_n );
    sensitive << ( img_0_data_stream_1_V_full_n );
    sensitive << ( img_0_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln25_fu_107_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln23_fu_95_p2 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Loop_out_proc24_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, img_0_data_stream_0_V_din, "(port)img_0_data_stream_0_V_din");
    sc_trace(mVcdFile, img_0_data_stream_0_V_full_n, "(port)img_0_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_0_data_stream_0_V_write, "(port)img_0_data_stream_0_V_write");
    sc_trace(mVcdFile, img_0_data_stream_1_V_din, "(port)img_0_data_stream_1_V_din");
    sc_trace(mVcdFile, img_0_data_stream_1_V_full_n, "(port)img_0_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_0_data_stream_1_V_write, "(port)img_0_data_stream_1_V_write");
    sc_trace(mVcdFile, img_0_data_stream_2_V_din, "(port)img_0_data_stream_2_V_din");
    sc_trace(mVcdFile, img_0_data_stream_2_V_full_n, "(port)img_0_data_stream_2_V_full_n");
    sc_trace(mVcdFile, img_0_data_stream_2_V_write, "(port)img_0_data_stream_2_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, img_0_data_stream_0_V_blk_n, "img_0_data_stream_0_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln25_fu_107_p2, "icmp_ln25_fu_107_p2");
    sc_trace(mVcdFile, img_0_data_stream_1_V_blk_n, "img_0_data_stream_1_V_blk_n");
    sc_trace(mVcdFile, img_0_data_stream_2_V_blk_n, "img_0_data_stream_2_V_blk_n");
    sc_trace(mVcdFile, row_fu_101_p2, "row_fu_101_p2");
    sc_trace(mVcdFile, row_reg_127, "row_reg_127");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, col_fu_113_p2, "col_fu_113_p2");
    sc_trace(mVcdFile, ap_block_state3, "ap_block_state3");
    sc_trace(mVcdFile, p_Val2_1_reg_73, "p_Val2_1_reg_73");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, p_Val2_s_reg_84, "p_Val2_s_reg_84");
    sc_trace(mVcdFile, icmp_ln23_fu_95_p2, "icmp_ln23_fu_95_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Loop_out_proc24::~Loop_out_proc24() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void Loop_out_proc24::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln23_fu_95_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !((esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_0_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_1_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_2_V_full_n.read()))) && 
         esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_1))) {
        p_Val2_1_reg_73 = row_reg_127.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_Val2_1_reg_73 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_0_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_1_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_2_V_full_n.read()))))) {
        p_Val2_s_reg_84 = col_fu_113_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln23_fu_95_p2.read()))) {
        p_Val2_s_reg_84 = ap_const_lv10_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        row_reg_127 = row_fu_101_p2.read();
    }
}

void Loop_out_proc24::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Loop_out_proc24::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Loop_out_proc24::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void Loop_out_proc24::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Loop_out_proc24::thread_ap_block_state3() {
    ap_block_state3 = ((esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_0_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_1_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_2_V_full_n.read())));
}

void Loop_out_proc24::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln23_fu_95_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Loop_out_proc24::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Loop_out_proc24::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void Loop_out_proc24::thread_col_fu_113_p2() {
    col_fu_113_p2 = (!p_Val2_s_reg_84.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(p_Val2_s_reg_84.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void Loop_out_proc24::thread_icmp_ln23_fu_95_p2() {
    icmp_ln23_fu_95_p2 = (!p_Val2_1_reg_73.read().is_01() || !ap_const_lv10_258.is_01())? sc_lv<1>(): sc_lv<1>(p_Val2_1_reg_73.read() == ap_const_lv10_258);
}

void Loop_out_proc24::thread_icmp_ln25_fu_107_p2() {
    icmp_ln25_fu_107_p2 = (!p_Val2_s_reg_84.read().is_01() || !ap_const_lv10_320.is_01())? sc_lv<1>(): sc_lv<1>(p_Val2_s_reg_84.read() == ap_const_lv10_320);
}

void Loop_out_proc24::thread_img_0_data_stream_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0))) {
        img_0_data_stream_0_V_blk_n = img_0_data_stream_0_V_full_n.read();
    } else {
        img_0_data_stream_0_V_blk_n = ap_const_logic_1;
    }
}

void Loop_out_proc24::thread_img_0_data_stream_0_V_din() {
    img_0_data_stream_0_V_din = p_Val2_s_reg_84.read().range(8-1, 0);
}

void Loop_out_proc24::thread_img_0_data_stream_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_0_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_1_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_2_V_full_n.read()))))) {
        img_0_data_stream_0_V_write = ap_const_logic_1;
    } else {
        img_0_data_stream_0_V_write = ap_const_logic_0;
    }
}

void Loop_out_proc24::thread_img_0_data_stream_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0))) {
        img_0_data_stream_1_V_blk_n = img_0_data_stream_1_V_full_n.read();
    } else {
        img_0_data_stream_1_V_blk_n = ap_const_logic_1;
    }
}

void Loop_out_proc24::thread_img_0_data_stream_1_V_din() {
    img_0_data_stream_1_V_din = ap_const_lv8_0;
}

void Loop_out_proc24::thread_img_0_data_stream_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_0_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_1_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_2_V_full_n.read()))))) {
        img_0_data_stream_1_V_write = ap_const_logic_1;
    } else {
        img_0_data_stream_1_V_write = ap_const_logic_0;
    }
}

void Loop_out_proc24::thread_img_0_data_stream_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0))) {
        img_0_data_stream_2_V_blk_n = img_0_data_stream_2_V_full_n.read();
    } else {
        img_0_data_stream_2_V_blk_n = ap_const_logic_1;
    }
}

void Loop_out_proc24::thread_img_0_data_stream_2_V_din() {
    img_0_data_stream_2_V_din = ap_const_lv8_0;
}

void Loop_out_proc24::thread_img_0_data_stream_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_0_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_1_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_2_V_full_n.read()))))) {
        img_0_data_stream_2_V_write = ap_const_logic_1;
    } else {
        img_0_data_stream_2_V_write = ap_const_logic_0;
    }
}

void Loop_out_proc24::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln23_fu_95_p2.read()))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void Loop_out_proc24::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void Loop_out_proc24::thread_row_fu_101_p2() {
    row_fu_101_p2 = (!p_Val2_1_reg_73.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(p_Val2_1_reg_73.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void Loop_out_proc24::thread_start_out() {
    start_out = real_start.read();
}

void Loop_out_proc24::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void Loop_out_proc24::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln23_fu_95_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !((esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_0_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_1_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_2_V_full_n.read()))) && esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_0_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_1_V_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln25_fu_107_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_0_data_stream_2_V_full_n.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

