# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/trevor/dev/myelect/video_mandel_gen/proj_1/proj_1.srcs/sources_1/bd/test_VPG_bd/ip/test_VPG_bd_video_mandelbrot_gen_0_0/test_VPG_bd_video_mandelbrot_gen_0_0.xci
# IP: The module: 'test_VPG_bd_video_mandelbrot_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/trevor/dev/myelect/video_mandel_gen/proj_1/proj_1.srcs/sources_1/bd/test_VPG_bd/ip/test_VPG_bd_video_mandelbrot_gen_0_0/constraints/video_mandelbrot_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_VPG_bd_video_mandelbrot_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/trevor/dev/myelect/video_mandel_gen/proj_1/proj_1.srcs/sources_1/bd/test_VPG_bd/ip/test_VPG_bd_video_mandelbrot_gen_0_0/test_VPG_bd_video_mandelbrot_gen_0_0.xci
# IP: The module: 'test_VPG_bd_video_mandelbrot_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/trevor/dev/myelect/video_mandel_gen/proj_1/proj_1.srcs/sources_1/bd/test_VPG_bd/ip/test_VPG_bd_video_mandelbrot_gen_0_0/constraints/video_mandelbrot_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_VPG_bd_video_mandelbrot_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
